import os
import glob
import pandas as pd
import numpy as np
from scipy.stats import poisson

from .load import save_to_csv
from .config import DATA_DIR


def merge_leagues(data_dir):
    """
   Combine raw season CSVs into a single clean dataset.
    """
    # Find all the downloaded CSVs
    files = glob.glob(os.path.join(data_dir, "turkey_20*_20*.csv"))

    # Read and combine them into a single DataFrame
    df_list = [pd.read_csv(file) for file in files]
    master_df = pd.concat(df_list, ignore_index=True)

    clean_df = master_df[['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'HC', 'AC', 'HY', 'AY', 'HS', 'AS']].copy()

    # Sort chronologically just to be safe
    clean_df['Date'] = pd.to_datetime(clean_df['Date'], dayfirst=True)
    clean_df = clean_df.sort_values(by='Date').reset_index(drop=True)

    # Save your new, massive, clean dataset!
    save_to_csv(clean_df, "turkey_master_clean.csv", data_dir)
    print("Data combined successfully!")
    return clean_df


def calculate_poisson_features(data_dir):
    """
    Engineer Poisson features (attack/defense strengths, lambda, scoreline probabilities).
    """
    # Load the combined dataset generated by the previous script
    df = pd.read_csv(os.path.join(data_dir, "turkey_master_clean.csv"))

    # Calculate the overall league average for home and away goals
    league_home_avg = df['FTHG'].mean()
    league_away_avg = df['FTAG'].mean()

    # Calculate the average goals scored and conceded by each team when playing at home
    home_stats = df.groupby('HomeTeam').agg(
        H_av_goals=('FTHG', 'mean'),
        H_conceded=('FTAG', 'mean')
    ).reset_index()

    # Calculate the average goals scored and conceded by each team when playing away
    away_stats = df.groupby('AwayTeam').agg(
        A_av_goals=('FTAG', 'mean'),
        A_conceded=('FTHG', 'mean')
    ).reset_index()

    # Merge the home and away stats back into the main dataframe
    df = df.merge(home_stats, on='HomeTeam', how='left')
    df = df.merge(away_stats, on='AwayTeam', how='left')

    # Calculate the attack strength by comparing team averages to the league average
    df['H attack'] = df['H_av_goals'] / league_home_avg
    df['A attack'] = df['A_av_goals'] / league_away_avg

    # Calculate the defense strength by comparing team goals conceded to the league average
    df['H def'] = df['H_conceded'] / league_away_avg
    df['A def'] = df['A_conceded'] / league_home_avg

    # Calculate expected goals (lambda) using the attack and defense strengths
    df['lambda h'] = df['H attack'] * df['A def'] * league_home_avg
    df['lambda a'] = df['A attack'] * df['H def'] * league_away_avg

    # Calculate exact scoreline probabilities using the Poisson probability mass function
    df['P(0 0)'] = poisson.pmf(0, df['lambda h']) * poisson.pmf(0, df['lambda a'])
    df['P(0 1)'] = poisson.pmf(0, df['lambda h']) * poisson.pmf(1, df['lambda a'])
    df['P(1 0)'] = poisson.pmf(1, df['lambda h']) * poisson.pmf(0, df['lambda a'])
    df['P(1 1)'] = poisson.pmf(1, df['lambda h']) * poisson.pmf(1, df['lambda a'])

    # Save the updated dataframe with all the new engineered features
    save_to_csv(df, "turkey_poisson_features.csv", data_dir)
    print("Poisson features calculated and saved to turkey_poisson_features.csv")
    return df


def calculate_form_features(data_dir):
    """
    Calculate form-based features (win rates, goals per game).
    """
    # Load the dataset containing the previously calculated Poisson features
    df = pd.read_csv(os.path.join(data_dir, "turkey_poisson_features.csv"))

    # Create binary flags for match outcomes based on goals scored
    df['h win'] = (df['FTHG'] > df['FTAG']).astype(int)
    df['h draw'] = (df['FTHG'] == df['FTAG']).astype(int)
    df['a win'] = (df['FTAG'] > df['FTHG']).astype(int)
    df['A D'] = (df['FTAG'] == df['FTHG']).astype(int)

    # Calculate points earned using the standard 3-1-0 point system
    df['h p'] = (df['h win'] * 3) + (df['h draw'] * 1)
    df['a p'] = (df['a win'] * 3) + (df['A D'] * 1)

    # Calculate the goal difference for the match from the home team's perspective
    df['gd'] = df['FTHG'] - df['FTAG']

    # Aggregate total games, wins, and goals scored for teams playing at home
    home_stats = df.groupby('HomeTeam').agg(
        home_games=('HomeTeam', 'count'),
        home_wins=('h win', 'sum'),
        home_goals=('FTHG', 'sum')
    ).reset_index()

    # Aggregate total games, wins, and goals scored for teams playing away
    away_stats = df.groupby('AwayTeam').agg(
        away_games=('AwayTeam', 'count'),
        away_wins=('a win', 'sum'),
        away_goals=('FTAG', 'sum')
    ).reset_index()

    # Calculate home and away win rates as percentages
    home_stats['h win rt'] = (home_stats['home_wins'] / home_stats['home_games']) * 100
    away_stats['a win rt'] = (away_stats['away_wins'] / away_stats['away_games']) * 100

    # Create a consolidated dataframe to calculate overall goals per game for each team
    team_totals = pd.DataFrame({'team_name': home_stats['HomeTeam']})
    team_totals = team_totals.merge(home_stats, left_on='team_name', right_on='HomeTeam')
    team_totals = team_totals.merge(away_stats, left_on='team_name', right_on='AwayTeam')

    # Calculate the overall goals per game metric across all fixtures
    total_goals_scored = team_totals['home_goals'] + team_totals['away_goals']
    total_matches_played = team_totals['home_games'] + team_totals['away_games']
    team_totals['gpg'] = total_goals_scored / total_matches_played

    # Merge the home win rates into the main dataset
    df = df.merge(
        home_stats[['HomeTeam', 'h win rt']], 
        on='HomeTeam', 
        how='left'
    )

    # Merge the away win rates into the main dataset
    df = df.merge(
        away_stats[['AwayTeam', 'a win rt']], 
        on='AwayTeam', 
        how='left'
    )

    # Merge the overall goals per game into the main dataset based on the home team
    df = df.merge(
        team_totals[['team_name', 'gpg']], 
        left_on='HomeTeam', 
        right_on='team_name', 
        how='left'
    ).drop(columns=['team_name'])

    # Save the fully updated dataset to a new CSV file
    save_to_csv(df, "turkey_form_and_poisson_features.csv", data_dir)
    print("Form features calculated and saved to turkey_form_and_poisson_features.csv")
    return df


def calculate_overall_probabilities(data_dir):
    """
   Generate bivariate Poisson match probabilities (Home Win, Draw, Away Win).
    """
    def calculate_match_probabilities(row, max_goals=10):
        """
        Generates a matrix of scoreline probabilities and sums them to find 
        the overall likelihood of a Home Win, Draw, or Away Win.
        """
        home_expected = row['lambda h']
        away_expected = row['lambda a']
        
        # Generate arrays of probabilities for scoring 0 through max_goals
        goals_range = np.arange(max_goals)
        home_probs = poisson.pmf(goals_range, home_expected)
        away_probs = poisson.pmf(goals_range, away_expected)
        
        # Create the bivariate probability matrix (home goals on rows, away goals on columns)
        prob_matrix = np.outer(home_probs, away_probs)
        
        # Sum the lower triangle where Home Goals (rows) > Away Goals (columns)
        p_home = np.tril(prob_matrix, k=-1).sum()
        
        # Sum the main diagonal where Home Goals == Away Goals
        p_draw = np.trace(prob_matrix)
        
        # Sum the upper triangle where Home Goals < Away Goals
        p_away = np.triu(prob_matrix, k=1).sum()
        
        return pd.Series([p_home, p_draw, p_away])

    # Load the dataset from the previous form calculation script
    df = pd.read_csv(os.path.join(data_dir, "turkey_form_and_poisson_features.csv"))

    # Apply the probability calculation across the dataframe
    df[['P(h)', 'P(d)', 'P(A)']] = df.apply(calculate_match_probabilities, axis=1)

    # Save the dataset with the new overall probabilities
    save_to_csv(df, "turkey_overall_probabilities.csv", data_dir)
    print("Overall match probabilities calculated and saved to turkey_overall_probabilities.csv")
    return df


def apply_dixon_coles_and_secondary_metrics(data_dir):
    """
   Apply Dixon-Coles rho adjustment and calculate expected corners/cards.
    """
    df = pd.read_csv(os.path.join(data_dir, "turkey_overall_probabilities.csv"))

    # A standard starting rho value in football modeling is typically around -0.15
    rho = -0.15

    # Store original probabilities to accurately adjust the overall match outcomes
    old_p00 = df['P(0 0)'].copy()
    old_p10 = df['P(1 0)'].copy()
    old_p01 = df['P(0 1)'].copy()
    old_p11 = df['P(1 1)'].copy()

    # Apply the Dixon-Coles tau adjustment functions to the low-scoring probabilities
    df['P(0 0)'] = old_p00 * (1 - df['lambda h'] * df['lambda a'] * rho)
    df['P(1 0)'] = old_p10 * (1 + df['lambda a'] * rho)
    df['P(0 1)'] = old_p01 * (1 + df['lambda h'] * rho)
    df['P(1 1)'] = old_p11 * (1 - rho)

    df['P(d)'] = df['P(d)'] - old_p00 - old_p11 + df['P(0 0)'] + df['P(1 1)']
    df['P(h)'] = df['P(h)'] - old_p10 + df['P(1 0)']
    df['P(A)'] = df['P(A)'] - old_p01 + df['P(0 1)']

    # CORNERS AND YELLOW CARDS EXPECTED VALUES
    # Calculate global league averages for secondary metrics
    league_hc_avg = df['HC'].mean()
    league_ac_avg = df['AC'].mean()
    league_hy_avg = df['HY'].mean()
    league_ay_avg = df['AY'].mean()

    # Calculate team-specific average corners and cards at home
    home_secondary = df.groupby('HomeTeam').agg(
        hc_for=('HC', 'mean'),
        hc_against=('AC', 'mean'),
        hy_for=('HY', 'mean'),
        hy_against=('AY', 'mean')
    ).reset_index()

    # Calculate team-specific average corners and cards away
    away_secondary = df.groupby('AwayTeam').agg(
        ac_for=('AC', 'mean'),
        ac_against=('HC', 'mean'),
        ay_for=('AY', 'mean'),
        ay_against=('HY', 'mean')
    ).reset_index()

    # Merge the secondary stats back into the main dataframe
    df = df.merge(home_secondary, on='HomeTeam', how='left')
    df = df.merge(away_secondary, on='AwayTeam', how='left')

    # Calculate Expected Corners for the specific match
    df['exp_home_corners'] = (df['hc_for'] / league_hc_avg) * (df['ac_against'] / league_hc_avg) * league_hc_avg
    df['exp_away_corners'] = (df['ac_for'] / league_ac_avg) * (df['hc_against'] / league_ac_avg) * league_ac_avg

    # Calculate Expected Yellow Cards for the specific match
    df['exp_home_yellows'] = (df['hy_for'] / league_hy_avg) * (df['ay_against'] / league_hy_avg) * league_hy_avg
    df['exp_away_yellows'] = (df['ay_for'] / league_ay_avg) * (df['hy_against'] / league_ay_avg) * league_ay_avg

    # Clean up the intermediate columns used for calculation
    df = df.drop(columns=[
        'hc_for', 'hc_against', 'hy_for', 'hy_against',
        'ac_for', 'ac_against', 'ay_for', 'ay_against'
    ])

    # Save the updated dataframe
    save_to_csv(df, "turkey_advanced_metrics.csv", data_dir)
    print("Dixon-Coles adjustment and secondary metrics saved to turkey_advanced_metrics.csv")
    return df


def apply_bayesian_posterior_update(data_dir):
    """
    Apply Gamma-Poisson Bayesian update using head-to-head records.
    """
    # Load the dataset containing the adjusted probabilities and secondary metrics
    df = pd.read_csv(os.path.join(data_dir, "turkey_advanced_metrics.csv"))

    # Ensure the dataset is sorted chronologically to prevent data leakage in the rolling H2H calculation
    df['Date'] = pd.to_datetime(df['Date'])
    df = df.sort_values(by='Date').reset_index(drop=True)

    # Dictionary to store cumulative head-to-head records for each matchup
    h2h_records = {}

    # Lists to collect the updated posterior probabilities row by row
    post_p_h = []
    post_p_d = []
    post_p_a = []

    for index, row in df.iterrows():
        home_team = row['HomeTeam']
        away_team = row['AwayTeam']
        matchup = (home_team, away_team)
        
        # Initialize the matchup tracking if these teams have not played yet
        if matchup not in h2h_records:
            h2h_records[matchup] = {
                'matches': 0, 
                'h_wins': 0, 
                'draws': 0, 
                'a_wins': 0
            }
            
        # Retrieve the historical head-to-head data prior to this specific match
        history = h2h_records[matchup]
        beta = history['matches']
        obs_h = history['h_wins']
        obs_d = history['draws']
        obs_a = history['a_wins']
        
        # Apply the Gamma-Poisson Bayesian update if historical data exists
        if beta > 0:
            # Calculate alpha (the predicted outcomes based on prior probabilities)
            alpha_h = beta * row['P(h)']
            alpha_d = beta * row['P(d)']
            alpha_a = beta * row['P(A)']
            
            # Calculate alpha prime by adding the actual observed outcomes
            alpha_prime_h = alpha_h + obs_h
            alpha_prime_d = alpha_d + obs_d
            alpha_prime_a = alpha_a + obs_a
            
            # Normalize the alpha prime values to convert them back into probabilities
            total_alpha_prime = alpha_prime_h + alpha_prime_d + alpha_prime_a
            post_p_h.append(alpha_prime_h / total_alpha_prime)
            post_p_d.append(alpha_prime_d / total_alpha_prime)
            post_p_a.append(alpha_prime_a / total_alpha_prime)
        else:
            # Fallback to the base probabilities if there is no historical head-to-head data
            post_p_h.append(row['P(h)'])
            post_p_d.append(row['P(d)'])
            post_p_a.append(row['P(A)'])
            
        # Update the historical records with the current match's outcome for future iterations
        h2h_records[matchup]['matches'] += 1
        h2h_records[matchup]['h_wins'] += row['h win']
        h2h_records[matchup]['draws'] += row['h draw']
        h2h_records[matchup]['a_wins'] += row['a win']

    # Assign the final Bayesian posterior probabilities to the dataframe
    df['Post_P(h)'] = post_p_h
    df['Post_P(d)'] = post_p_d
    df['Post_P(A)'] = post_p_a

    # Save the finalized predictive dataset
    save_to_csv(df, "turkey_final_bayesian_model.csv", data_dir)
    print("Bayesian posterior probabilities calculated and saved to turkey_final_bayesian_model.csv")
    return df


def run_transform_pipeline():
    """
    Execute the full Transform → Load pipeline.
    
    Following the DS pipeline architecture 
    - Pre-processing Layer: Data preparation (merge raw seasons, clean)
    - Model Building Layer: Feature engineering + modeling (Poisson, form, Dixon-Coles, Bayesian)
    - Load: Each stage saves its output CSV to the data folder
    """
    # Pre-processing Layer: Data Preparation
    print("\n Data Preparation")
    merge_leagues(DATA_DIR)

    # Model Building Layer: Feature Engineering & Modeling
    print("\n Feature Engineering")
    calculate_poisson_features(DATA_DIR)
    calculate_form_features(DATA_DIR)

    print("\n Probability Modeling ")
    calculate_overall_probabilities(DATA_DIR)
    apply_dixon_coles_and_secondary_metrics(DATA_DIR)

    print("\n  Bayesian Update ")
    apply_bayesian_posterior_update(DATA_DIR)

    print("Pipeline complete. All CSV files saved to:", DATA_DIR)


if __name__ == "__main__":
    run_transform_pipeline()
