import pandas as pd
from scipy.stats import poisson

# Load the combined dataset generated by the previous script
df = pd.read_csv("turkey_master_clean.csv")

# Calculate the overall league average for home and away goals
league_home_avg = df['FTHG'].mean()
league_away_avg = df['FTAG'].mean()

# Calculate the average goals scored and conceded by each team when playing at home
home_stats = df.groupby('HomeTeam').agg(
    H_av_goals=('FTHG', 'mean'),
    H_conceded=('FTAG', 'mean')
).reset_index()

# Calculate the average goals scored and conceded by each team when playing away
away_stats = df.groupby('AwayTeam').agg(
    A_av_goals=('FTAG', 'mean'),
    A_conceded=('FTHG', 'mean')
).reset_index()

# Merge the home and away stats back into the main dataframe
df = df.merge(home_stats, on='HomeTeam', how='left')
df = df.merge(away_stats, on='AwayTeam', how='left')

# Calculate the attack strength by comparing team averages to the league average
df['H attack'] = df['H_av_goals'] / league_home_avg
df['A attack'] = df['A_av_goals'] / league_away_avg

# Calculate the defense strength by comparing team goals conceded to the league average
df['H def'] = df['H_conceded'] / league_away_avg
df['A def'] = df['A_conceded'] / league_home_avg

# Calculate expected goals (lambda) using the attack and defense strengths
df['lambda h'] = df['H attack'] * df['A def'] * league_home_avg
df['lambda a'] = df['A attack'] * df['H def'] * league_away_avg

# Calculate exact scoreline probabilities using the Poisson probability mass function
df['P(0 0)'] = poisson.pmf(0, df['lambda h']) * poisson.pmf(0, df['lambda a'])
df['P(0 1)'] = poisson.pmf(0, df['lambda h']) * poisson.pmf(1, df['lambda a'])
df['P(1 0)'] = poisson.pmf(1, df['lambda h']) * poisson.pmf(0, df['lambda a'])
df['P(1 1)'] = poisson.pmf(1, df['lambda h']) * poisson.pmf(1, df['lambda a'])

# Save the updated dataframe with all the new engineered features
df.to_csv("turkey_poisson_features.csv", index=False)
print("Poisson features calculated and saved to turkey_poisson_features.csv")
